version: '3.7'

services:
  backend:
    build: backend
    volumes:
      - ./backend/:/app
    environment:
      - DB_ENGINE=${DJANGO_DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DJANGO_DB_HOST}
      - DB_PORT=${DJANGO_DB_PORT}
      - BACKEND_PORT=${BACKEND_PORT}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - COLLECT_STATIC=${DJANGO_COLLECT_STATIC}
      - CREATE_SUPER_USER=${DJANGO_CREATE_SUPER_USER}
      - LOAD_DUMPS=${DJANGO_LOAD_DUMPS}
    depends_on:
      - db
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  nginx:
    image: nginx:alpine
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_HTTPS_PORT}:443
    environment:
      - DOMAIN=${DOMAIN}
      - BACKEND_PORT=${BACKEND_PORT}
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/templates:/etc/nginx/templates:rw,cached
      - ./backend/static/:/app/static/
      - ./backend/media/:/app/media/
      - ./backend/docs/build/html/:/app/backend/docs/build/html/
    restart: always
    depends_on:
      - backend
  redis:
    image: redis
volumes:
  postgres_data:
