# Generated by Django 4.0.5 on 2022-06-19 09:59

from django.db import migrations, models
import music_room.models


class Migration(migrations.Migration):

    dependencies = [
        ('music_room', '0003_track_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_file',
            field=models.FileField(upload_to='music', validators=[music_room.models.audio_file_validator]),
        ),
    ]
