# Generated by Django 4.0.5 on 2022-06-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_room', '0004_alter_track_track_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='track_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='track_file',
            new_name='file',
        ),
    ]
