# Generated by Django 4.0.5 on 2022-06-19 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_room', '0005_rename_track_duration_track_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='tracks',
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='playlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music_room.playlist'),
            preserve_default=False,
        ),
    ]
