# Generated by Django 4.0.5 on 2022-06-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_room', '0006_remove_playlist_tracks_playlisttrack_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontrack',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
