# Generated by Django 4.0.5 on 2022-07-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_room', '0007_sessiontrack_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='access_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=50),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='type',
            field=models.CharField(choices=[('default', 'Default'), ('custom', 'Custom')], default='custom', max_length=50),
        ),
    ]
