# Generated by Django 4.0.5 on 2022-07-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_room', '0008_playlist_access_type_alter_playlist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontrack',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
