# Generated by Django 4.0.5 on 2022-07-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_room', '0009_alter_sessiontrack_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlisttrack',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
