# Generated by Django 4.0.5 on 2022-07-16 21:38

from django.db import migrations, models
import django.db.models.deletion
import music_room.models


class Migration(migrations.Migration):

    dependencies = [
        ('music_room', '0010_alter_playlisttrack_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='track',
            name='file',
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='music', validators=[music_room.models.audio_file_validator])),
                ('extension', models.CharField(choices=[('mp3', 'Mp3'), ('flac', 'Flac')], max_length=50)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='music_room.track')),
            ],
        ),
    ]
