# Generated by Django 4.0.5 on 2022-07-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_room', '0011_remove_track_duration_remove_track_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='extension',
            field=models.CharField(blank=True, choices=[('mp3', 'Mp3'), ('flac', 'Flac')], max_length=50, null=True),
        ),
    ]
