# Generated by Django 4.0.5 on 2022-08-07 22:52

from django.db import migrations, models
import music_room.models


class Migration(migrations.Migration):

    dependencies = [
        ('music_room', '0012_alter_file_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(help_text='Send highest quality file, lowest will be make automatically<br>Allowed:<br> mp3<br>flac', upload_to='music', validators=[music_room.models.audio_file_validator]),
        ),
    ]
