# Generated by Django 4.0.5 on 2022-08-11 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_room', '0013_alter_file_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='TrackFile',
        ),
    ]
