# Generated by Django 4.1.2 on 2022-10-23 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("music_room", "0016_event_alter_playlistaccess_playlist_eventaccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="playersession",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_player_session",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
