# Generated by Django 3.2.15 on 2022-10-23 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_room', '0017_playersession_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music_room.playlist'),
        ),
    ]
