# Generated by Django 3.2.15 on 2022-10-23 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_room', '0018_event_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='playlist',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='music_room.playlist'),
        ),
        migrations.AlterField(
            model_name='eventaccess',
            name='access_mode',
            field=models.CharField(choices=[('guest', 'Only view'), ('moderator', 'Edit playlist, invite users'), ('administrator', "Edit playlist, invite users, change user's access mode")], default='guest', max_length=50),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='type',
            field=models.CharField(choices=[('default', 'Default'), ('custom', 'Custom'), ('temporary', 'Temporary')], default='custom', max_length=50),
        ),
    ]
