# Generated by Django 3.2.15 on 2022-10-23 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_room', '0019_auto_20221023_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playersession',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='player_session',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='music_room.playersession'),
        ),
    ]
